spring.application.name=inventory-service

server.port=8081

spring.datasource.url=jdbc:sqlite:inventory-service.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

aws.region=us-east-1
aws.sqs.inventory-queue-url=YOUR_INVENTORY_QUEUE_URL